Php->Java socket
vitrine-info-cegep/vitrine-info-cegep-site-web pull request #1
Opened 2023-03-10 19:49 UTC by LarochelleJ

2023-03-10 23:27 UTC, 2143781-Ouellette-Antoine requested changes
Pourrais-tu mettre test-api.php dans dev/
Est-ce que c'est volontaire les espaces vides que tu as rajouté?

2023-03-12 22:47 UTC, LarochelleJ commented on include/configuration.inc
> +
Les espaces sont voulues

2023-03-12 22:47 UTC, LarochelleJ commented on dev/test-api.php
> +<?php
Fichier test-api.php déplacé dans /dev

2023-03-12 22:48 UTC, LarochelleJ reviewed
Changement apporté

2023-03-14 14:23 UTC, merged